---
title: "Generate figures"
author: "Abby Lewis"
format: html
editor: visual
---

This file generates three figures for the Scientific Data publication.

## Load packages and data

```{r}
#Load packages
library(tidyverse)
library(ggthemes)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
#remotes::install_github("ropensci/rnaturalearthhires")
library(rnaturalearthhires)
library(ggspatial)
library(lwgeom)
library(cowplot)
library(patchwork)

#Load data from EDI
metadata <- read_delim("https://pasta.lternet.edu/package/data/eml/edi/2220/2/fadd3eaa25b5fdd1fc4efba70e660579")
data <- read_delim("https://pasta.lternet.edu/package/data/eml/edi/2220/2/ca2482ef3c43f053ae13cdf2bf5ba7a8")
```

## Map study sites (Figure 1)

Information about Winkel Tripel projection: <https://wilkelab.org/practicalgg/articles/Winkel_tripel.html>

```{r}
#Load basemap
world <- ne_countries(scale = "medium", returnclass = "sf")
crs_wintri <- "+proj=wintri +datum=WGS84 +no_defs +over"
world_wintri <- st_transform_proj(world, crs = crs_wintri)

disp_win_wgs84 <- st_sfc(st_point(c(-180, -80)), st_point(c(180, 80)),
                         crs = 4326)
disp_win_trans <- st_transform(disp_win_wgs84, crs = crs_wintri)
disp_win_coord <- st_coordinates(disp_win_trans)

#Set graticule
grat_wintri <- 
  st_graticule(x = c(-180, -90, 180, 90),
               crs = st_crs(4326),
               lat = c(-89.9, seq(-90, 90, 20), 89.9),
               ) %>%
  st_transform_proj(crs = crs_wintri)
meta_wintri <- st_transform_proj(st_as_sf(metadata, coords = c("Longitude", "Latitude"), crs = 4326), crs = crs_wintri)
meta_wintri <- data %>%
  group_by(LakeID) %>%
  summarize(CH4 = ifelse(sum(!is.na(CH4_umolL))>0, 1, 0),
            CO2 = ifelse(sum(!is.na(CO2_umolL))>0, 1, 0)) %>%
  mutate(Data_avail = ifelse(CH4 + CO2 == 2,
                             "Both",
                             ifelse(CH4 == 1, "CH[4]",
                                    ifelse(CO2 == 1, "CO[2]", NA)))) %>%
  left_join(metadata) %>%
  filter(!is.na(Latitude)) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>%
  st_transform_proj(crs = crs_wintri) 

# vectors of latitudes and longitudes that go around the 
# globe in 1-degree steps
lat_min <- -90
lat_max <- 90
lon_min <- -180
lon_max <- 180
lats <- c(lat_max:lat_min, rep(lat_min, lon_max-lon_min+1), 
          lat_min:lat_max, rep(lat_max, lon_max-lon_min+1))
longs <- c(rep(lon_max, lat_max-lat_min+1), lon_max:lon_min, 
           rep(lon_min, lat_max-lat_min+1), lon_min:lon_max)

# turn into correctly projected sf collection
wintri_outline <- 
  list(cbind(longs, lats)) %>%
  st_polygon() %>%
  st_sfc( # create sf geometry list column
    crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
  ) %>% 
  st_sf() %>%
  st_transform_proj(crs = crs_wintri) # transform to Winkel tripel

#Summarize number of lakes for each gas
ns <- meta_wintri %>%
  group_by(Data_avail) %>%
  summarize(n = length(unique(LakeID)))

both <- ns$n[ns$Data_avail == "Both"]
ch4 <- ns$n[ns$Data_avail == "CH[4]"]
co2 <- ns$n[ns$Data_avail == "CO[2]"]

#Plot!
map <- ggplot(data = world_wintri) +
  geom_sf(data = wintri_outline,
    fill = "grey93", size = 0.5/.pt) + 
  geom_sf(data = grat_wintri, color = "black", size = 0.5, alpha = 0.1) + 
  geom_sf(fill = "white", color = "grey70", size = 0.5/.pt) +
  geom_sf(data = meta_wintri %>% filter(Data_avail == "CO[2]"),
          aes(fill = Data_avail),shape = 21, color = "white", 
          size = 2, alpha  =.5, stroke = .4)+
  geom_sf(data = meta_wintri %>% filter(Data_avail == "CH[4]"),
          aes(fill = Data_avail),shape = 21, color = "white", 
          size = 2, alpha  =.5, stroke = .4)+
  geom_sf(data = meta_wintri %>% filter(Data_avail == "Both"),
          aes(fill = Data_avail),shape = 21, color = "white", 
          size = 2, alpha  =.5, stroke = .4)+
  coord_sf(datum = NULL)+
  scale_fill_manual(values = c("#000000","#922D50","#006989"),
                    name = "Data availability",
                    labels = c(bquote(CH[4]~"and"~CO[2]~"("*italic(n)~"="~.(both)*")"), 
                               bquote(CH[4]~"only ("*italic(n)~"="~.(ch4)*")"),
                               bquote(CO[2]~"only  ("*italic(n)~"="~.(co2)*")")))+
  theme(plot.margin = ggplot2::margin(0, 0, 0, 0, "cm"),
        plot.background = element_rect(fill = "white"),
        legend.position = "bottom",
        legend.text = element_text(margin = margin(l = 0.1)),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        panel.background = element_rect(fill = "white"),
        legend.margin = margin(t = -10, unit = "pt"))

#Now do subplots for two particularly dense regions
#Europe
bbox_coords <- st_bbox(c(xmin = -8.9, ymin = 35.2, 
                         xmax = 28, ymax = 72.2))
bbox_polygon <- st_as_sf(st_as_sfc(st_bbox(bbox_coords)), crs = 4326)
bbox_proj <- bbox_polygon %>% st_transform_proj(crs = "+proj=wintri")
eu <- map +
  coord_sf(
    xlim = st_bbox(bbox_proj)[c(1,3)],
    ylim = st_bbox(bbox_proj)[c(2,4)],
    expand = FALSE
    ) +
  annotation_scale(location = "br", width_hint = 0.3, height = unit(0.1, "cm")) +
  theme(legend.position = "none",
        panel.border = element_rect(colour = "black", fill=NA, linewidth=0.7))

#USA
usa_states <- st_as_sf(maps::map("state", fill = TRUE, plot = FALSE))
bbox_coords <- st_bbox(c(xmin = -102, ymin = 26, 
                         xmax = -72, ymax = 50))
bbox_polygon <- st_as_sf(st_as_sfc(st_bbox(bbox_coords)), crs = 4326)
bbox_proj <- bbox_polygon %>% st_transform_proj(crs = "EPSG:5070")
usa <- map +
  geom_sf(data = usa_states, aes(fill = "State"), 
          color = "grey70", fill = NA, size=0.125) +
  coord_sf(
    xlim = st_bbox(bbox_proj)[c(1,3)],
    ylim = st_bbox(bbox_proj)[c(2,4)],
    expand = FALSE,
    crs = "EPSG:5070"
    ) +
  annotation_scale(location = "br", width_hint = 0.3, height = unit(0.1, "cm")) +
  theme(legend.position = "none",
        panel.border = element_rect(colour = "black", fill=NA, linewidth=0.7))


#full map
map2 <- map + theme(plot.margin = unit(c(0.5, 5.5, 1.5, 56.5), "pt")) 
full <- map2 %>% 
  ggdraw() +
  draw_plot(usa,
    x = -0.05, 
    y = 0.15,
    width = 0.36, 
    height = 0.36) +
  draw_plot(eu,
    x = -0.07, 
    y = 0.53,
    width = 0.4, 
    height = 0.4)
  
ggsave(plot = full, filename = "../Figures/map_inserts.jpeg", width = 6, 
       height = 3.5, units = "in", dpi = 300)
```

## Metadata summary stats (Figure 2)

Histograms for key variables

```{r}
depth <- metadata %>% 
  filter(Focal_site == TRUE) %>%
  group_by(LakeID) %>%
  summarize(MaximumDepth_m = mean(MaximumDepth_m, na.rm = T)) %>%
  ggplot(aes(x = MaximumDepth_m))+
  geom_density()+
  scale_x_log10(n.breaks = 5)+
  scale_x_log10(breaks = c(1, 10, 100, 1000), 
                labels = c("1", "10", "100","1,000"))+
  theme_bw()+
  xlab(expression("Maximum depth (m)")) +
  theme(axis.title.x = element_text(vjust = 1,
                                    margin = margin(t = 7.1)),
        axis.text.x = element_text(angle = 30, hjust = 1))

area <- metadata %>% 
  filter(Focal_site == TRUE) %>%
  group_by(LakeID) %>%
  summarize(SurfaceArea_km2 = mean(SurfaceArea_km2, na.rm = T)) %>%
  ggplot(aes(x = SurfaceArea_km2))+
  geom_density()+
  scale_x_log10(n.breaks = 3, breaks = c(0.0001, 0.01, 1, 100, 100000), 
                labels = c("0.0001", "0.01", "1", "100","100,000"))+
  theme_bw()+
  xlab(expression("Surface area ("*km^2*")"))+
  theme(axis.title.x = element_text(vjust = 1),
        axis.text.x = element_text(angle = 30, hjust = 1))

phos <- metadata %>% 
  filter(Focal_site == TRUE) %>%
  group_by(LakeID) %>%
  summarize(TP_ugL_mean = mean(TP_ugL_mean, na.rm = T)) %>%
  ggplot(aes(x = TP_ugL_mean))+
  geom_density()+
  scale_x_log10(labels = scales::label_comma(drop0trailing = T))+
  theme_bw()+
  xlab(expression("Total phosphorus ("*mu*"g L"^-1*")"))+
  theme(axis.title.x = element_text(vjust = 1),
        axis.text.x = element_text(angle = 30, hjust = 1))

years <- data %>%
  mutate(Year = year(Date)) %>%
  filter(!is.na(CO2_umolL)|!is.na(CH4_umolL)) %>%
  group_by(Year, LakeID) %>%
  summarize() %>% 
  ggplot(aes(x = Year))+
  geom_density()+
  theme_bw()+
  scale_x_continuous(n.breaks = 5)

doys <- data %>%
  left_join(metadata %>%
              select(LakeID, Latitude)) %>%
  mutate(Date = as.Date(Date),
         Date = ifelse(Latitude < 0, Date + months(6), Date),
         Date = as.Date(Date)) %>%
  filter(!is.na(CO2_umolL)|!is.na(CH4_umolL)) %>%
  mutate(yday = lubridate::yday(Date)) %>%
  group_by(LakeID, yday) %>%
  summarize() %>%
  ggplot(aes(x = yday))+
  geom_density()+
  xlab("Sampling date")+
  theme_bw()+
  scale_x_continuous(breaks = c(82, 266),
                     labels = c("spring\nequinox",
                                "autumn\nequinox"),
                     limits = c(0,365))+
  theme(axis.title.x = element_text(vjust = 0.5))

lats <- metadata %>% 
  filter(Focal_site == TRUE) %>%
  group_by(LakeID, Latitude) %>%
  summarize() %>%
  ggplot(aes(x = Latitude))+
  geom_density()+
  xlab("Latitude (degrees)")+
  theme_bw()+
  scale_x_continuous(breaks = scales::breaks_pretty(n = 5))+
  theme(axis.title.x = element_text(vjust = 0.5))

#Combine and save
top <- lats + years + doys + plot_layout(axis_titles = "collect")
bottom <- phos + area + depth + plot_layout(axis_titles = "collect") 

data_plots <- top/bottom + plot_annotation(tag_levels = 'a')
ggsave(plot = data_plots, filename = "../Figures/data_plots.jpeg", width = 6, 
       height = 4, units = "in", dpi = 300)
```

## Concentration density plots (Figure 3)

```{r}
min <- min(c(data$CO2_umolL, data$CH4_umolL), na.rm = T)
max <- max(c(data$CO2_umolL, data$CH4_umolL), na.rm = T)

layer_dat <- data %>% 
  left_join(metadata) %>%
  group_by(LakeID, LakeName, Source, Site, Date) %>%
  mutate(layer = case_when(Depth_m == min(Depth_m) ~ "Surface",
                           Depth_m == max(Depth_m) ~ "Bottom")) %>%
  ungroup() %>%
  mutate(layer = ifelse(layer == "Surface" & Depth_m > MaximumDepth_m*.33,
                        NA, layer)) %>%
  mutate(layer = ifelse(layer == "Bottom" & Depth_m < MaximumDepth_m*.5,
                        NA, layer)) %>%
  mutate(layer = factor(layer, levels = c("Surface", "Bottom"))) %>%
  filter(!is.na(layer))
  
co2 <- layer_dat %>% 
  ggplot(aes(x = layer, y = CO2_umolL)) +
  geom_violin() +
  geom_boxplot(width = 0.1, outlier.size = 0.7, outlier.shape = 1) +
  scale_y_log10(labels = scales::label_comma(drop0trailing = T),
                n.breaks = 5) +
  theme_bw() +
  labs(y = expression("CO"[2]*" ("*mu*"M)"), x = "Layer") +
  theme(axis.title.x = element_blank())

ch4 <- layer_dat %>% 
  ggplot(aes(x = layer, y = CH4_umolL)) +
  geom_violin() +
  geom_boxplot(width = 0.1, outlier.size = 0.7, outlier.shape = 1) +
  scale_y_log10(labels = scales::label_comma(drop0trailing = T)) +
  theme_bw() +
  labs(y = expression("CH"[4]*" ("*mu*"M)"), x = "Layer") +
  theme(axis.title.x = element_blank())

do <- layer_dat %>% 
  ggplot(aes(x = layer, y = DO_mgL)) +
  geom_violin() +
  geom_boxplot(width = 0.1, outlier.size = 0.7, outlier.shape = 1) +
  theme_bw() +
  labs(y = expression("DO (mg L"^-1*")"), x = "Layer")

temp <- layer_dat %>% 
  ggplot(aes(x = layer, y = Temp_C)) +
  geom_violin() +
  geom_boxplot(width = 0.1, outlier.size = 0.7, outlier.shape = 1) +
  theme_bw() +
  labs(y = expression("Temp (C)"), x = "Layer")

#Combine and save
var_plots <- (co2+ch4)/(do+temp) + plot_annotation(tag_levels = 'a')
var_plots
ggsave(plot = var_plots, filename = "../Figures/var_plots.jpeg", width = 5, 
       height = 4, units = "in", dpi = 300)
```
